export const loginConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED"
}

export const quizDataConstants = {
    ADD_QUIZ_DATA_REQUEST: "ADD_QUIZ_DATA_REQUEST",
    ADD_QUIZ_DATA_SUCCESS: "ADD_QUIZ_DATA_SUCCESS",
    ADD_QUIZ_DATA_FAILED: "ADD_QUIZ_DATA_FAILED",
    UPDATE_QUIZ_SCORE: "UPDATE_QUIZ_SCORE"
}
